### ISSUE TITLE
Tried to compile code on linux and it failed

### ISSUE THREAD

**Issue by thomashaury** [lvandeve/oopoker#1]
Undefined symbols for architecture x86_64:
  "getDateString()", referenced from:
      ObserverLog::ObserverLog(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in observer_log-f069ce.o
      benchmarkEval7() in unittest-ee71ed.o
  "getRandomUint()", referenced from:
      getRandom() in random-ad984a.o
      getRandom(int, int) in random-ad984a.o
      seedRandomFastWithRandomSlow() in random-ad984a.o
  "getCharNonBlocking()", referenced from:
      HostTerminal::onFrame() in host_terminal-c49449.o
  "getChar()", referenced from:
      AIHuman::boastCards(Info const&) in ai_human-c721f0.o
      HostTerminal::onGameDone(Info const&) in host_terminal-c49449.o
      pressAnyKeyOrQuit() in io_terminal-73dc05.o
      pressAnyKey() in io_terminal-73dc05.o
      doGame() in main-ee5cc8.o
  "getLine()", referenced from:
      editOptions(Options&) in ai_human-c721f0.o
      AIHuman::doTurn(Info const&) in ai_human-c721f0.o
      doGame() in main-ee5cc8.o
      runConsolePotEquityCalculator() in tools_terminal-7ca3ce.o
      runConsoleShowdownCalculator() in tools_terminal-7ca3ce.o
  "sleepMS(int)", referenced from:
      AIHuman::onEvent(Event const&) in ai_human-c721f0.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lvandeve** [comment]
Which compile command did you use?

Does the following work?

g++ -O3 *.cpp -o oopoker

or alternatively:

clang++ -O3 *.cpp -o oopoker

Thanks you

**Comment by thomashaury** [comment]
I get the same error every time although this time I don't see any of the warnings.

I am on MacOS Mojave I hope that doesn't matter.

Previosuly I used the command: 

g++ *.cpp -W -Wall -Wextra -ansi 

Here is a screen shot of the error I get all 3 ways I have tried including your new ways

<img width="1155" alt="Screen Shot 2019-10-30 at 11 11 28 AM" src="https://user-images.githubusercontent.com/14005623/67886673-178d7480-fb07-11e9-9157-84a6fc06e3e5.png">

**Comment by lvandeve** [comment]
I pushed a possible fix with commit 0b72e6aa8aa77854314609464f1f8347e549c984

It will depend on if you have "/dev/urandom" and the headers <termios.h>, <unistd.h> and <fcntl.h> available on your operating system, please let me know if you get any more errors

**Comment by thomashaury** [comment]
Yea I was looking at a possible fix as well I will try mine and test yours and see if either solution works and get back

**Comment by thomashaury** [comment]
So it says fatal error "os.h" file not found.

**Comment by lvandeve** [comment]
Oops, I forgot to git add os.h. It's here now:
https://github.com/lvandeve/oopoker/blob/master/os.h

**Comment by thomashaury** [comment]
Wow works great now :) This is super awesome. Thank You so much for helping me and making this. You're a great programmer.
